# Generated by Django 3.0.5 on 2021-12-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20211208_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='TxvRostelecom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200, verbose_name='Логин')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('id_lid', models.CharField(max_length=50, verbose_name='ID лида')),
                ('region', models.CharField(max_length=200, verbose_name='Область')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('house', models.CharField(max_length=50, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, max_length=50, verbose_name='Кв.')),
                ('available_connect', models.TextField(blank=True, verbose_name='ТхВ')),
                ('tarifs_all', models.TextField(blank=True, verbose_name='Тарифы')),
                ('pv_address', models.TextField(blank=True, verbose_name='ПВ адрес')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Запрос поступил'), (1, 'Бот забрал запрос'), (2, 'Ошибка обработки запроса'), (3, 'Запрос отработан')], verbose_name='Статус')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('bot_log', models.TextField(blank=True, verbose_name='Лог бота')),
            ],
        ),
    ]
